
["Animation Settings"]
	#Entities that won't play target animations (format: modid:entity_id)
	#Example: ["minecraft:wither", "minecraft:ender_dragon"]
	animationBlacklist = ["minecraft:wither", "minecraft:ender_dragon", "efn:sin_summoned_sword", "efn:doppelganger", "evil_thought:treeking"]
	#Entities that can play Yamato's stun animations (format: modid:entity_id)
	#Example: ["minecraft:player", "minecraft:zombie", "minecraft:skeleton"]
	animationWhitelist = ["minecraft:creeper", "wom:evil_skeleton", "wom:hollow", "wom:saulomonk", "wom:lycanth"]

