
["Animation Settings"]
	#Entities that won't play Yamato's stun animations (format: modid:entity_id)
	#Example: ["minecraft:wither", "minecraft:ender_dragon"]
	animationBlacklist = ["minecraft:wither", "minecraft:ender_dragon", "efn:sin_summoned_sword", "efn:doppelganger", "evil_thought:treeking"]
	#Entities that can play Yamato's stun animations (format: modid:entity_id)
	#Example: ["minecraft:player", "minecraft:zombie", "minecraft:skeleton"]
	animationWhitelist = ["minecraft:creeper", "wom:evil_skeleton", "wom:hollow", "wom:saulomonk", "wom:lycanth"]

["Yamato Catcher Settings"]
	#Entities that CANNOT be caught by Yamato Catcher (format: modid:entity_id)
	#These entities will be ignored regardless of knockback resistance
	#Example: ["minecraft:wither", "minecraft:ender_dragon"]
	yamatoCatcherBlacklist = ["minecraft:wither", "minecraft:ender_dragon"]
	#Entities that CAN be caught by Yamato Catcher (format: modid:entity_id)
	#These entities can be caught regardless of knockback resistance
	#Example: ["minecraft:player", "minecraft:zombie"]
	yamatoCatcherWhitelist = ["minecraft:zombie", "minecraft:drowned", "minecraft:husk", "minecraft:skeleton", "minecraft:wither_skeleton", "minecraft:stray", "minecraft:bogged", "minecraft:Pillager", "minecraft:evoker", "minecraft:vindicator", "minecraft:blaze", "minecraft:piglin", "minecraft:zombified_piglin", "minecraft:enderman"]

["Yamato  Global Stun Settings"]
	#Entities that can be Global Focus stunned by Yamato successful parry + attack combo (format: modid:entity_id)
	#These entities will receive YamatoStunEffect when hit
	#Use 'modid:all' to include all entities from a mod
	#Example: ["minecraft:zombie", "cataclysm:all", "iceandfire:all"]
	yamatoStunWhitelist = ["cataclysm:all"]

["Yamato Parry Stun Settings"]
	#Duration of stun effect applied after successful parry + attack combo (in ticks, 20 ticks = 1 second)
	#Range: 1 ~ 200
	yamatoParryStunDuration = 20
	#Cooldown between parry stuns (in ticks, 20 ticks = 1 second)
	#Range: 1 ~ 1200
	yamatoParryStunCooldown = 60

["JudgementCut-End Camera Animation Settings"]
	#Enable/disable camera animations for JudgementCut-End
	#When enabled, JudgementCut-End will play cinematic camera animations
	#Default: true (enabled)
	enableCameraAnimations = true

["Bloodlust Skill Post-effect Settings"]
	#Enable/disable post-effect when bloodlust's skill active
	#When enabled, bloodlust's skill will play post-effect
	#Default: true (enabled)
	enablePost-Effects = true

["Yamato Reward Settings"]
	#Enable/disable the skill book reward for Yamato JudgementCut-End
	#When enabled, players will receive JudgementCut-End skill book after reaching the kill threshold
	#Default: true (enabled)
	yamatoRewardEnabled = true
	#Number of kills required to receive the Yamato JudgementCut-End reward
	#Set to 0 to disable the reward system
	#Default: 100 kills
	#Range: 0 ~ 10000
	yamatoRewardKillThreshold = 500

["JudgementCut-End Particle Settings"]
	#Enable/disable particle effects for JudgementCut-End
	#Disable Judgement Cut End's particle effects that may cause rendering incompatibility
	#Default: true (enabled)
	enableJudgementCutEndParticles = true

["Judgement Cut End Damage Settings"]
	#Base damage rate for Judgement Cut End
	#This multiplies the base damage calculation
	#Default: 2.0
	#Range: 0.1 ~ 100.0
	judgementCutEndDamageRate = 2.0
	#Cut rate for Judgement Cut End (percentage of max health)
	#This determines how much percentage damage is dealt based on target's max health
	#Default: 0.4 (40%)
	#Range: 0.01 ~ 1.0
	judgementCutEndCutRate = 0.4
	#Damage multiplier against Cataclysm bosses
	#This multiplies the damage when attacking Cataclysm bosses
	#Default: 1.0 (no multiplier)
	#Range: 0.1 ~ 10.0
	judgementCutEndBossDamageMultiplier = 1.0
	#Health percentage used in damage calculation
	#This is the percentage of max health used in the formula: cutRate * (maxHealth * healthPercentage)
	#Default: 0.4 (40%)
	#Range: 0.01 ~ 1.0
	judgementCutEndHealthPercentage = 0.4

